[2025-10-04T17:47:16.247+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:16.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:47:16.249+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:47:16.249+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:16.265+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:47:16.260+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:47:16.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:16.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.049 seconds
[2025-10-04T17:47:46.579+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:46.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:47:46.580+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:47:46.580+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:46.594+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:47:46.592+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:47:46.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:47:46.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.025 seconds
[2025-10-04T17:48:16.870+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:16.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:48:16.872+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:48:16.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:16.887+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:48:16.886+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:48:16.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:16.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.027 seconds
[2025-10-04T17:48:47.175+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:47.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:48:47.179+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:48:47.178+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:47.197+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:48:47.195+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:48:47.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:48:47.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.034 seconds
[2025-10-04T17:49:17.545+0000] {processor.py:186} INFO - Started process (PID=427) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:17.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:49:17.547+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:49:17.547+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:17.563+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:49:17.561+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:49:17.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:17.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.028 seconds
[2025-10-04T17:49:47.917+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:47.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:49:47.920+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:49:47.919+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:47.937+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:49:47.936+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:49:47.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:49:47.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.030 seconds
[2025-10-04T17:50:18.290+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:18.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:50:18.293+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:50:18.293+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:18.310+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:50:18.308+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:50:18.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:18.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.030 seconds
[2025-10-04T17:50:48.612+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:48.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:50:48.614+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:50:48.614+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:48.630+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:50:48.629+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:50:48.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:50:48.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.029 seconds
[2025-10-04T17:51:18.986+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:18.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:51:18.989+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:51:18.989+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:19.008+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:51:19.006+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:51:19.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:19.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.033 seconds
[2025-10-04T17:51:49.331+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:49.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:51:49.333+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:51:49.333+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:49.348+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:51:49.346+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:51:49.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:51:49.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.026 seconds
[2025-10-04T17:52:19.698+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:19.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:52:19.701+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:52:19.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:19.716+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:52:19.715+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:52:19.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:19.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.029 seconds
[2025-10-04T17:52:49.999+0000] {processor.py:186} INFO - Started process (PID=538) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:49.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:52:50.001+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:52:50.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:50.014+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:52:50.012+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:52:50.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:52:50.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.024 seconds
[2025-10-04T17:53:20.327+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:20.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:53:20.330+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:53:20.329+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:20.345+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:53:20.344+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:53:20.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:20.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.029 seconds
[2025-10-04T17:53:50.683+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:50.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:53:50.685+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:53:50.685+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:50.702+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:53:50.701+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:53:50.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:53:50.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.030 seconds
[2025-10-04T17:54:21.005+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:21.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:54:21.009+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:54:21.009+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:21.027+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:54:21.026+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:54:21.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:21.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.034 seconds
[2025-10-04T17:54:51.369+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:51.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:54:51.372+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:54:51.372+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:51.388+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:54:51.387+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:54:51.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:54:51.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.030 seconds
[2025-10-04T17:55:21.727+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:21.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:55:21.730+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:55:21.729+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:21.746+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:55:21.744+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:55:21.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:21.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.029 seconds
[2025-10-04T17:55:52.087+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:52.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:55:52.090+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:55:52.089+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:52.109+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:55:52.107+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:55:52.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:55:52.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.034 seconds
[2025-10-04T17:56:22.404+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:22.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:56:22.408+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:56:22.407+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:22.428+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:56:22.426+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:56:22.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:22.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.035 seconds
[2025-10-04T17:56:52.780+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:52.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:56:52.782+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:56:52.782+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:52.798+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:56:52.797+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:56:52.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:56:52.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.028 seconds
[2025-10-04T17:57:23.340+0000] {processor.py:186} INFO - Started process (PID=688) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:23.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:57:23.346+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:57:23.346+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:23.367+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:57:23.365+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:57:23.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:23.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.036 seconds
[2025-10-04T17:57:53.846+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:53.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:57:53.849+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:57:53.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:53.865+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:57:53.864+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:57:53.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:57:53.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.030 seconds
[2025-10-04T17:58:24.210+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:24.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:58:24.213+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:24.213+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:24.231+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:24.230+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T17:58:24.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:24.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.032 seconds
[2025-10-04T17:58:54.640+0000] {processor.py:186} INFO - Started process (PID=751) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:54.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:58:54.643+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:54.642+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:54.658+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:54.658+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T17:58:54.659+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:54.659+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T17:58:54.659+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:54.659+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T17:58:54.660+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:54.660+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T17:58:55.540+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:58:55.579+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.579+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:TrainPredict
[2025-10-04T17:58:55.582+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.582+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:TrainPredict
[2025-10-04T17:58:55.584+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.584+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:TrainPredict
[2025-10-04T17:58:55.586+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.586+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:TrainPredict
[2025-10-04T17:58:55.587+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.587+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:TrainPredict
[2025-10-04T17:58:55.588+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.588+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:TrainPredict
[2025-10-04T17:58:55.590+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.590+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:TrainPredict
[2025-10-04T17:58:55.590+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.590+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T17:58:55.594+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.594+0000] {dag.py:3252} INFO - Creating ORM DAG for TrainPredict
[2025-10-04T17:58:55.597+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:58:55.597+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T17:58:55.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.968 seconds
[2025-10-04T17:59:26.186+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:26.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:59:26.189+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:26.208+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.208+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T17:59:26.209+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.209+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T17:59:26.209+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.209+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T17:59:26.210+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.210+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T17:59:26.719+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:26.768+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.768+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T17:59:26.776+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:26.776+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T17:59:26.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.604 seconds
[2025-10-04T17:59:56.926+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:56.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T17:59:56.928+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:56.928+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:56.939+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:56.939+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T17:59:56.940+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:56.940+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T17:59:56.940+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:56.940+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T17:59:56.940+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:56.940+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T17:59:57.322+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T17:59:57.372+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:57.372+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T17:59:57.380+0000] {logging_mixin.py:190} INFO - [2025-10-04T17:59:57.380+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T17:59:57.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.464 seconds
[2025-10-04T18:00:27.474+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:27.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:00:27.476+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:27.476+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:27.485+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:27.485+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:00:27.486+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:27.486+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:00:27.486+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:27.486+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:00:27.486+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:27.486+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:00:28.166+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:28.210+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:28.210+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:00:28.217+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:28.217+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:00:28.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.750 seconds
[2025-10-04T18:00:59.066+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:59.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:00:59.069+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.069+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:59.083+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.083+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:00:59.084+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.083+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:00:59.084+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.084+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:00:59.084+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.084+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:00:59.700+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:00:59.749+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.749+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:00:59.756+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:00:59.756+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:00:59.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.702 seconds
[2025-10-04T18:01:30.399+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:01:30.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:01:30.401+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.401+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:01:30.416+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.416+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:01:30.417+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.417+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:01:30.417+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.417+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:01:30.417+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.417+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:01:30.875+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:01:30.926+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.925+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:01:30.933+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:01:30.933+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:01:30.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.546 seconds
[2025-10-04T18:02:01.121+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:01.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:02:01.124+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.124+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:01.140+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.140+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:02:01.141+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.141+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:02:01.141+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.141+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:02:01.142+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.142+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:02:01.681+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:01.732+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.731+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:02:01.741+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:01.740+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:02:01.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.631 seconds
[2025-10-04T18:02:31.835+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:31.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:02:31.838+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:31.838+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:31.853+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:31.853+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:02:31.853+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:31.853+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:02:31.854+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:31.854+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:02:31.854+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:31.854+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:02:32.368+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:02:32.415+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:32.415+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:02:32.422+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:02:32.422+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:02:32.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.599 seconds
[2025-10-04T18:03:03.417+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:03.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:03:03.420+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.420+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:03.452+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.452+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:03:03.453+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.453+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:03:03.454+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.454+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:03:03.455+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.455+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:03:03.832+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:03.884+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.883+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:03:03.891+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:03.891+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:03:03.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.485 seconds
[2025-10-04T18:03:33.969+0000] {processor.py:186} INFO - Started process (PID=993) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:33.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:03:33.972+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:33.972+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:33.989+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:33.989+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:03:33.990+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:33.990+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:03:33.991+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:33.991+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:03:33.991+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:33.991+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:03:34.539+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:03:34.587+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:34.587+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:03:34.594+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:03:34.594+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:03:34.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.637 seconds
[2025-10-04T18:04:05.586+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:05.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:04:05.587+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:05.587+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:05.598+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:05.598+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:04:05.598+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:05.598+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:04:05.599+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:05.599+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:04:05.599+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:05.599+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:04:06.070+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:06.118+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:06.118+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:04:06.126+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:06.126+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-03 00:00:00+00:00, run_after=2025-10-04 00:00:00+00:00
[2025-10-04T18:04:06.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.550 seconds
[2025-10-04T18:04:37.160+0000] {processor.py:186} INFO - Started process (PID=1040) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:37.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:04:37.162+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.162+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:37.177+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.177+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:04:37.178+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.178+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:04:37.178+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.178+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:04:37.179+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.179+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:04:37.611+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:04:37.663+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.662+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:04:37.670+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:04:37.670+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:04:37.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.523 seconds
[2025-10-04T18:05:07.711+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:07.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:05:07.713+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:07.713+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:07.724+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:07.724+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:05:07.725+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:07.725+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:05:07.726+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:07.726+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:05:07.726+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:07.726+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:05:08.329+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:08.374+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:08.374+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:05:08.381+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:08.381+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:05:08.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.681 seconds
[2025-10-04T18:05:39.272+0000] {processor.py:186} INFO - Started process (PID=1082) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:39.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:05:39.274+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:39.283+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.283+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:05:39.284+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.284+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:05:39.284+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.284+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:05:39.285+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.285+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:05:39.709+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:05:39.757+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.757+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:05:39.765+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:05:39.765+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:05:39.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.503 seconds
[2025-10-04T18:06:09.835+0000] {processor.py:186} INFO - Started process (PID=1103) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:09.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:06:09.838+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:09.838+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:09.854+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:09.854+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:06:09.855+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:09.855+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:06:09.855+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:09.855+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:06:09.856+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:09.856+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:06:10.377+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:10.420+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:10.420+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:06:10.428+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:10.428+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:06:10.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.604 seconds
[2025-10-04T18:06:41.424+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:41.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:06:41.427+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:41.427+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:41.442+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:41.442+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:06:41.443+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:41.443+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:06:41.443+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:41.443+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:06:41.444+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:41.444+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:06:42.128+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:06:42.174+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:42.174+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:06:42.182+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:06:42.182+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:06:42.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.769 seconds
[2025-10-04T18:07:12.711+0000] {processor.py:186} INFO - Started process (PID=1145) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:12.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:07:12.714+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:12.714+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:12.730+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:12.730+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:07:12.731+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:12.731+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:07:12.731+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:12.731+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:07:12.732+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:12.732+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:07:13.114+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:13.164+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:13.164+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:07:13.172+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:13.172+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:07:13.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.473 seconds
[2025-10-04T18:07:43.517+0000] {processor.py:186} INFO - Started process (PID=1166) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:43.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:07:43.522+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.521+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:43.552+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.552+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:07:43.553+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.553+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:07:43.554+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.554+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:07:43.555+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.555+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:07:43.913+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:07:43.961+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.961+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:07:43.969+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:07:43.969+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:07:43.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.463 seconds
[2025-10-04T18:08:14.317+0000] {processor.py:186} INFO - Started process (PID=1187) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:14.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:08:14.320+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.320+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:14.335+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.335+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:08:14.336+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.336+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:08:14.336+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.336+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:08:14.337+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.337+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:08:14.889+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:14.939+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.939+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:08:14.947+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:14.947+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:08:14.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.643 seconds
[2025-10-04T18:08:45.141+0000] {processor.py:186} INFO - Started process (PID=1208) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:45.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:08:45.144+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.144+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:45.158+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.158+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:08:45.159+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.159+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:08:45.159+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.159+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:08:45.160+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.160+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:08:45.728+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:08:45.780+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.779+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:08:45.788+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:08:45.788+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:08:45.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.658 seconds
[2025-10-04T18:09:16.742+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:16.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:09:16.744+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:16.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:16.754+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:16.754+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:09:16.755+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:16.755+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:09:16.755+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:16.755+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:09:16.755+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:16.755+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:09:17.121+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:17.169+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:17.169+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:09:17.177+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:17.177+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:09:17.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.445 seconds
[2025-10-04T18:09:47.341+0000] {processor.py:186} INFO - Started process (PID=1250) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:47.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:09:47.351+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:47.351+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:47.366+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:47.365+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:09:47.369+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:47.369+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:09:47.371+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:47.371+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:09:47.371+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:47.371+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:09:47.954+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:09:48.006+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:48.006+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:09:48.016+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:09:48.016+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:09:48.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.686 seconds
[2025-10-04T18:10:18.493+0000] {processor.py:186} INFO - Started process (PID=1271) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:18.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:10:18.495+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:18.495+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:18.513+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:18.513+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:10:18.514+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:18.514+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:10:18.515+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:18.515+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:10:18.515+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:18.515+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:10:18.989+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:19.037+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:19.037+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:10:19.045+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:19.045+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:10:19.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.565 seconds
[2025-10-04T18:10:49.215+0000] {processor.py:186} INFO - Started process (PID=1292) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:49.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:10:49.217+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.217+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:49.232+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.232+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:10:49.232+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.232+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:10:49.233+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.233+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:10:49.233+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.233+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:10:49.700+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:10:49.734+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.734+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:10:49.740+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:10:49.740+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:10:49.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.536 seconds
[2025-10-04T18:11:19.762+0000] {processor.py:186} INFO - Started process (PID=1313) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:19.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:11:19.764+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:19.764+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:19.773+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:19.773+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:11:19.774+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:19.774+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:11:19.774+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:19.774+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:11:19.774+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:19.774+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:11:20.423+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:20.467+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:20.467+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:11:20.475+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:20.475+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:11:20.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.721 seconds
[2025-10-04T18:11:51.109+0000] {processor.py:186} INFO - Started process (PID=1334) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:51.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:11:51.112+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.112+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:51.127+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.127+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:11:51.128+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.128+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:11:51.129+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.128+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:11:51.129+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.129+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:11:51.525+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:11:51.564+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.564+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:11:51.572+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:11:51.572+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:11:51.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.473 seconds
[2025-10-04T18:12:21.954+0000] {processor.py:186} INFO - Started process (PID=1355) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:21.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:12:21.957+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:21.957+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:21.973+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:21.972+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:12:21.974+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:21.973+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:12:21.974+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:21.974+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:12:21.975+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:21.975+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:12:22.326+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:22.376+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:22.375+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:12:22.385+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:22.384+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:12:22.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.442 seconds
[2025-10-04T18:12:52.689+0000] {processor.py:186} INFO - Started process (PID=1376) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:52.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:12:52.691+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:52.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:52.703+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:52.703+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:12:52.703+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:52.703+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:12:52.704+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:52.704+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:12:52.704+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:52.704+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:12:53.229+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:12:53.278+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:53.278+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:12:53.287+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:12:53.287+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:12:53.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.609 seconds
[2025-10-04T18:13:24.223+0000] {processor.py:186} INFO - Started process (PID=1397) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:24.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:13:24.226+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.225+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:24.240+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.240+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:13:24.241+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.241+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:13:24.241+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.241+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:13:24.242+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.242+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:13:24.747+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:24.797+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.797+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:13:24.804+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:24.804+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:13:24.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.593 seconds
[2025-10-04T18:13:55.773+0000] {processor.py:186} INFO - Started process (PID=1418) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:55.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:13:55.775+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:55.775+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:55.784+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:55.784+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-04T18:13:55.785+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:55.785+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-04T18:13:55.785+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:55.785+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-04T18:13:55.786+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:55.785+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-04T18:13:56.485+0000] {processor.py:925} INFO - DAG(s) 'TrainPredict' retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:13:56.532+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:56.531+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-10-04T18:13:56.540+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:13:56.540+0000] {dag.py:4156} INFO - Setting next_dagrun for TrainPredict to 2025-10-04 00:00:00+00:00, run_after=2025-10-05 00:00:00+00:00
[2025-10-04T18:13:56.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.776 seconds
[2025-10-04T18:14:45.772+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:14:45.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:14:45.775+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:14:45.775+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:14:45.786+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:14:45.785+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:14:45.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:14:45.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.025 seconds
[2025-10-04T18:15:16.605+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:16.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:15:16.607+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:15:16.607+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:16.620+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:15:16.619+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:15:16.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:16.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.024 seconds
[2025-10-04T18:15:47.113+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:47.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:15:47.116+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:15:47.116+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:47.131+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:15:47.128+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:15:47.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:15:47.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.029 seconds
[2025-10-04T18:16:17.755+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:17.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:16:17.757+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:16:17.757+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:17.769+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:16:17.767+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:16:17.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:17.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.022 seconds
[2025-10-04T18:16:48.264+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:48.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:16:48.266+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:16:48.266+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:48.278+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:16:48.277+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:16:48.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:16:48.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.022 seconds
[2025-10-04T18:17:18.905+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:18.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:17:18.908+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:17:18.908+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:18.923+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:17:18.921+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:17:18.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:18.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.026 seconds
[2025-10-04T18:17:49.402+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:49.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:17:49.404+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:17:49.403+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:49.418+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:17:49.417+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:17:49.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:17:49.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.025 seconds
[2025-10-04T18:18:19.964+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:19.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:18:19.967+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:18:19.966+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:19.978+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:18:19.977+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:18:19.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:19.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.022 seconds
[2025-10-04T18:18:50.527+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:50.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:18:50.529+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:18:50.529+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:50.551+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:18:50.546+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:18:50.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:18:50.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.035 seconds
[2025-10-04T18:19:21.113+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:21.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:19:21.115+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:19:21.115+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:21.129+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:19:21.128+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:19:21.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:21.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.025 seconds
[2025-10-04T18:19:51.647+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:51.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:19:51.650+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:19:51.650+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:51.669+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:19:51.665+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:19:51.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:19:51.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.031 seconds
[2025-10-04T18:20:22.228+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:22.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:20:22.230+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:20:22.230+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:22.242+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:20:22.241+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:20:22.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:22.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.023 seconds
[2025-10-04T18:20:52.852+0000] {processor.py:186} INFO - Started process (PID=534) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:52.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:20:52.854+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:20:52.854+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:52.867+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:20:52.866+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:20:52.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:20:52.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.023 seconds
[2025-10-04T18:21:23.484+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:23.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:21:23.487+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:21:23.487+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:23.509+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:21:23.508+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:21:23.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:23.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.037 seconds
[2025-10-04T18:21:54.084+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:54.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:21:54.087+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:21:54.087+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:54.101+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:21:54.099+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:21:54.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:21:54.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.024 seconds
[2025-10-04T18:22:24.774+0000] {processor.py:186} INFO - Started process (PID=603) to work on /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:22:24.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_market_ml_forecasting_dag.py for tasks to queue
[2025-10-04T18:22:24.781+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:22:24.781+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:22:24.801+0000] {logging_mixin.py:190} INFO - [2025-10-04T18:22:24.800+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/stock_market_ml_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 87, in <module>
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_market_ml_forecasting_dag.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2025-10-04T18:22:24.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_ml_forecasting_dag.py
[2025-10-04T18:22:24.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_market_ml_forecasting_dag.py took 0.035 seconds
